spring:
  application:
    name: payment-batch
  datasource:
    url: jdbc:postgresql://localhost:5432/bbv_db
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: Always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 🚀 CONFIGURAÇÕES DO SPRING BATCH EM YAML:
  batch:
    job:
      enabled: false # Impede o job de rodar sozinho ao ligar o projeto
    jdbc:
      initialize-schema: always # Cria as tabelas de controle do Batch (BATCH_JOB_INSTANCE, etc.) automaticamente

server:
  port: ${SERVER_PORT:8200}